name: NuGet Pack for .NET MAUI Library

on:
  push:
    branches:
      - main

jobs:
  pack:
    runs-on: macos-14

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
          sudo xcodebuild -runFirstLaunch

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.400' # Specify your MAUI-compatible SDK version

      - name: Install MAUI workloads
        run: dotnet workload install maui

      # image cropper
      - name: Restore NuGet packages
        run: dotnet restore Plugin.Maui.ImageCropper/Plugin.Maui.ImageCropper.csproj

      - name: Pack NuGet package
        run: |
          dotnet pack Plugin.Maui.ImageCropper/Plugin.Maui.ImageCropper.csproj --configuration Release --output ./nupkgs
  
      - name: Publish NuGet package
        run: |
          dotnet nuget push ./nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}

      # android binding
      - name: Restore NuGet packages
        run: dotnet restore ImageCropper.Maui.Binding.Android/ImageCropper.Maui.Binding.Android.csproj

      - name: Pack NuGet package
        run: |
          dotnet pack ImageCropper.Maui.Binding.Android/ImageCropper.Maui.Binding.Android.csproj --configuration Release --output ./nupkgs/android
  
      - name: Publish NuGet package
        run: |
          dotnet nuget push ./nupkgs/android/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate

      # iOS binding
      - name: Restore NuGet packages
        run: dotnet restore ImageCropper.Maui.Binding.iOS/ImageCropper.Maui.Binding.iOS.csproj

      - name: Pack NuGet package
        run: |
          dotnet pack ImageCropper.Maui.Binding.iOS/ImageCropper.Maui.Binding.iOS.csproj --configuration Release --output ./nupkgs/ios
  
      - name: Publish NuGet package
        run: |
          dotnet nuget push ./nupkgs/ios/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate

